// Email validation utility to block temporary/burner email services
const TEMP_EMAIL_DOMAINS = [
  // Popular temporary email services
  "10minutemail.com",
  "20minutemail.com",
  "guerrillamail.com",
  "mailinator.com",
  "tempmail.org",
  "temp-mail.org",
  "yopmail.com",
  "maildrop.cc",
  "throwaway.email",
  "getnada.com",
  "sharklasers.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "pokemail.net",
  "spam4.me",
  "grr.la",
  "guerrillamail.de",
  "trbvm.com",
  "byom.de",
  "spamgourmet.com",
  "spaml.de",
  "spamgourmet.net",
  "spamgourmet.org",
  "mailnesia.com",
  "mailcatch.com",
  "mailmetrash.com",
  "nomail.xl.cx",
  "noemailspam.com",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "tempinbox.com",
  "tmpemail.co.uk",
  "2prong.com",
  "spamherelots.com",
  "spamhereplease.com",
  "spamthisplease.com",
  "sendspamhere.com",
  "chogmail.com",
  "cook.dm",
  "myspamless.com",
  "put2.net",
  "quickinbox.com",
  "rcpt.at",
  "realtyalerts.ca",
  "recode.me",
  "recursor.net",
  "regbypass.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "ru.ru",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "selfdestructingmail.com",
  "selfdestructingmail.org",
  "sendspamhere.com",
  "sharklasers.com",
  "shiftmail.com",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "siteposter.net",
  "skeefmail.com",
  "slopsbox.com",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakmail.de",
  "snkmail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soodonims.com",
  "spam4.me",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.net",
  "spamfree24.org",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spami.spam.co.za",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtrail.com",
  "spamtroll.net",
  "temp-mail.org",
  "tempail.com",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz",
  "tempemail.com",
  "tempinbox.co.uk",
  "tempinbox.com",
  "tempmail.eu",
  "tempmaildemo.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempomail.fr",
  "temporarily.de",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tempthe.net",
  "thankyou2010.com",
  "thecloudindex.com",
  "thelimestones.com",
  "themapixelglobal.com",
  "thewolfinfo.com",
  "thisgoesinthebin.com",
  "throwam.com",
  "throwaway.email",
  "throwawayemailaddresses.com",
  "tinyurl.com",
  "tmail.ws",
  "tmpemail.co.uk",
  "tmpjr.com",
  "tmpmail.org",
  "tmpmail.net",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash2009.com",
  "trashdevil.com",
  "trashemail.de",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com",
  "trashymail.net",
  "trbvm.com",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "upliftnow.com",
  "uplipht.com",
  "uroid.com",
  "us.af",
  "venompen.com",
  "veryrealemail.com",
  "vidchart.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "walala.org",
  "walkmail.net",
  "webemail.me",
  "webm4il.info",
  "webuser.in",
  "wh4f.org",
  "whatiaas.com",
  "whatpaas.com",
  "whatsaas.com",
  "whopy.com",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "www.e4ward.com",
  "www.gishpuppy.com",
  "www.mailinator.com",
  "wwwnew.eu",
  "x.ip6.li",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",
  "yomail.info",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yourdomain.com",
  "yourewrongheresjohnny.com",
  "yourisp.net",
  "yourmailprovider.com",
  "ypmail.webredirect.org",
  "yuurok.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zetmail.com",
  "zigiabi.com",
  "zoemail.org",
  "zomg.info",
  "percyfx.com", // The example you provided
  "dropmail.me",
  "emailondeck.com",
  "fakeinbox.com",
  "hidemail.de",
  "incognitomail.org",
  "jetable.org",
  "mailforspam.com",
  "meltmail.com",
  "mohmal.com",
  "mytrashmail.com",
  "no-spam.ws",
  "nospam.ze.tc",
  "nowmymail.com",
  "oneoffmail.com",
  "pookmail.com",
  "proxymail.eu",
  "rootfest.net",
  "spamfighter.cf",
  "spamfighter.ga",
  "spamfighter.gq",
  "spamfighter.ml",
  "spamfighter.tk",
  "superrito.com",
  "tempr.email",
  "throwaway.technology",
  "tmail.ws",
];

// List of trusted email providers (major providers)
const TRUSTED_EMAIL_PROVIDERS = [
  "gmail.com",
  "yahoo.com",
  "outlook.com",
  "hotmail.com",
  "live.com",
  "msn.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "aol.com",
  "protonmail.com",
  "tutanota.com",
  "zoho.com",
  "fastmail.com",
  "yandex.com",
  "mail.ru",
  "qq.com",
  "163.com",
  "126.com",
  "sina.com",
  "sohu.com",
  "ukr.net",
  "rambler.ru",
  "gmx.com",
  "gmx.de",
  "web.de",
  "t-online.de",
  "freenet.de",
  "libero.it",
  "virgilio.it",
  "alice.it",
  "tin.it",
  "orange.fr",
  "laposte.net",
  "sfr.fr",
  "bbox.fr",
  "wanadoo.fr",
];

export function isValidBusinessEmail(email: string): {
  isValid: boolean;
  reason?: string;
} {
  if (!email || typeof email !== "string") {
    return { isValid: false, reason: "Email is required" };
  }

  // Basic email format validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return { isValid: false, reason: "Invalid email format" };
  }

  const domain = email.toLowerCase().split("@")[1];

  if (!domain) {
    return { isValid: false, reason: "Invalid email domain" };
  }

  // Check if it's a temporary/burner email domain
  if (TEMP_EMAIL_DOMAINS.includes(domain)) {
    return {
      isValid: false,
      reason:
        "Temporary email addresses are not allowed. Please use a permanent email address from a trusted provider like Gmail, Yahoo, or Outlook.",
    };
  }

  // Check for suspicious patterns
  if (
    domain.includes("temp") ||
    domain.includes("disposable") ||
    domain.includes("throw") ||
    domain.includes("spam") ||
    domain.includes("trash") ||
    domain.includes("fake") ||
    domain.includes("burner") ||
    domain.includes("guerrilla") ||
    domain.length < 4
  ) {
    return {
      isValid: false,
      reason:
        "Suspicious email domain detected. Please use a trusted email provider.",
    };
  }

  // If it's a trusted provider, it's definitely valid
  if (TRUSTED_EMAIL_PROVIDERS.includes(domain)) {
    return { isValid: true };
  }

  // For other domains (business emails, etc.), we'll allow them
  // but we could add additional validation here if needed
  return { isValid: true };
}

export function isDuplicateUser(
  email: string,
  existingEmails: string[]
): boolean {
  return existingEmails.some(
    (existingEmail) => existingEmail.toLowerCase() === email.toLowerCase()
  );
}
